import type {
  CitationProposal,
  CitationValidationResult,
  RetrievalResult,
  ImmutableProvenanceSnapshot,
  CitationRecord
} from "./contracts.ts";

/**
 * Validates a proposed citation against the current retrieval context.
 * This is a pure function that deterministically decides if a citation is valid.
 */
export function validateCitationProposal(
  proposal: CitationProposal,
  retrievalContext: RetrievalResult[],
  generateId: () => string
): CitationValidationResult {
  // 1. Proposed Chunk ID exists in current retrieval context.
  const chunk = retrievalContext.find((c) => c.chunkId === proposal.chunkId);
  if (!chunk) {
    return {
      status: "INVALID",
      reason: "Chunk ID not found in retrieval context",
    };
  }

  const { provenance } = chunk;

  // 2. Source authorization is valid according to the supplied metadata.
  if (
    provenance.legalClearance !== "CLEARED" ||
    provenance.verificationStatus !== "PUBLISHED"
  ) {
    return {
      status: "INVALID",
      reason: "Source is not legally cleared and published",
    };
  }

  // 3. Provenance snapshot is constructed from the validated evidence
  // PYQ authenticity status is preserved implicitly by copying the entire server-side provenance.
  const authoritativeProvenance: ImmutableProvenanceSnapshot = { ...provenance };

  // 4. Final authoritative Citation ID is generated by system logic.
  const citationId = `CIT-${generateId()}`;

  return {
    status: "VALID",
    citationId,
    provenance: authoritativeProvenance,
  };
}

/**
 * Helper to process an array of citation proposals.
 * Returns valid CitationRecords and drops invalid ones.
 */
export function processCitations(
  proposals: CitationProposal[],
  retrievalContext: RetrievalResult[],
  generateId: () => string
): CitationRecord[] {
  const records: CitationRecord[] = [];
  
  for (const proposal of proposals) {
    // 5. Citation proposal is structurally valid (has chunkId).
    if (!proposal.chunkId) continue;
    
    const result = validateCitationProposal(proposal, retrievalContext, generateId);
    if (result.status === "VALID" && result.citationId && result.provenance) {
      records.push({
        citationId: result.citationId,
        chunkId: proposal.chunkId,
        provenance: result.provenance,
      });
    }
  }
  
  return records;
}
